package main

var allowdHosts = map[string]bool{
	"igcdn-photos-a-a.akamaihd.net":      true,
	"igcdn-photos-b-a.akamaihd.net":      true,
	"igcdn-photos-c-a.akamaihd.net":      true,
	"igcdn-photos-d-a.akamaihd.net":      true,
	"igcdn-photos-e-a.akamaihd.net":      true,
	"igcdn-photos-f-a.akamaihd.net":      true,
	"igcdn-photos-g-a.akamaihd.net":      true,
	"igcdn-photos-h-a.akamaihd.net":      true,
	"igcdn-photos-i-a.akamaihd.net":      true,
	"igcdn-photos-j-a.akamaihd.net":      true,
	"igcdn-photos-k-a.akamaihd.net":      true,
	"igcdn-photos-l-a.akamaihd.net":      true,
	"igcdn-photos-m-a.akamaihd.net":      true,
	"igcdn-photos-n-a.akamaihd.net":      true,
	"igcdn-photos-o-a.akamaihd.net":      true,
	"igcdn-photos-p-a.akamaihd.net":      true,
	"igcdn-photos-q-a.akamaihd.net":      true,
	"igcdn-photos-r-a.akamaihd.net":      true,
	"igcdn-photos-s-a.akamaihd.net":      true,
	"igcdn-photos-t-a.akamaihd.net":      true,
	"igcdn-photos-u-a.akamaihd.net":      true,
	"igcdn-photos-v-a.akamaihd.net":      true,
	"igcdn-photos-w-a.akamaihd.net":      true,
	"igcdn-photos-x-a.akamaihd.net":      true,
	"distillery.s3.amazonaws.com":        true,
	"distilleryimage0.s3.amazonaws.com":  true,
	"distilleryimage1.s3.amazonaws.com":  true,
	"distilleryimage2.s3.amazonaws.com":  true,
	"distilleryimage3.s3.amazonaws.com":  true,
	"distilleryimage4.s3.amazonaws.com":  true,
	"distilleryimage5.s3.amazonaws.com":  true,
	"distilleryimage6.s3.amazonaws.com":  true,
	"distilleryimage7.s3.amazonaws.com":  true,
	"distilleryimage8.s3.amazonaws.com":  true,
	"distilleryimage9.s3.amazonaws.com":  true,
	"distilleryimage10.s3.amazonaws.com": true,
	"distilleryimage11.s3.amazonaws.com": true,
	"images.ak.instagram.com":            true,
	"origincache-ash.fbcdn.net":          true,
	"origincache-frc.fbcdn.net":          true,
	"origincache-prn.fbcdn.net":          true,
	"photos-a.ak.instagram.com":          true,
	"photos-b.ak.instagram.com":          true,
	"photos-c.ak.instagram.com":          true,
	"photos-d.ak.instagram.com":          true,
	"photos-e.ak.instagram.com":          true,
	"photos-f.ak.instagram.com":          true,
	"photos-g.ak.instagram.com":          true,
	"photos-h.ak.instagram.com":          true,
	"scontent-a.cdninstagram.com":        true,
	"scontent-b.cdninstagram.com":        true,
	"scontent-c.cdninstagram.com":        true,
	"scontent-d.cdninstagram.com":        true,
	"scontent-e.cdninstagram.com":        true,
	"scontent-f.cdninstagram.com":        true,
	// "zhinsta.com:8080":                   true, // for debug
}

func isHostAllowed(host string) bool {
	_, ok := allowdHosts[host]
	return ok
}
